### ISSUE TITLE
Please run ‘minio’ as a non-root user.

### ISSUE THREAD

**Issue by jimmy0017** [slypix/minio-dokku#1]
When I push it to dokku, it showed up " minio: <ERROR> Please run ‘minio’ as a non-root user."

**Comment by OmgImAlexis** [comment]
Since this repo hasn't been updated in a while I made a new one that fixes this issue as well as uses the latest Minio server. https://github.com/OmgImAlexis/dokku-minio

If you want to keep using this repo then you'll need to add in `ENV ALLOW_CONTAINER_ROOT=1` to your Dockerfile as it states [here](https://github.com/minio/minio/pull/1327/files#diff-ebacf6f6ae4ee68078bb16454b23247dR8). I'm not 100% if that'll work though as I believe this repo is running an outdated version of Minio.

**Comment by slypix** [comment]
@OmgImAlexis thank you for looking into this, forking it and keeping it up to date.

I tried your solution `ENV ALLOW_CONTAINER_ROOT=1`, and didn't seem to help, however adding `USER dokku` to the Dockerfile did work in my test.

thanks again

**Comment by OmgImAlexis** [comment]
@slypix yeah I think that's because you're running an outdated version of minio that doesn't have the commit that added support for that.

**Comment by slypix** [comment]
@OmgImAlexis right, makes sense. So I finally had a chance to update my Dokku installation to 0.9.2, and updated/tested the Dockerfile with the latest minio version as well, so now all is working again.
