### ISSUE TITLE
Security Issue: Needs world write access to mounted storage

### ISSUE THREAD

**Issue by rosario-raulin** [slypix/minio-dokku#2]
We just set up a minio instance using this dockerfile on our server. As stated in your documentation, we had to give write permission to everyone on the host system for the mounted storage volume.

This is a potential security issue as only dokku should be able to read/write files from this directory. We is this necessary?

**Comment by slypix** [comment]
Iv'e tried using 755 permissions as recommended, but I couldn't get that to work on my dokku instance, however it does work fine on  a local server running docker. so I know it's not the docker image or minio, I have yet to figure out how to make dokku permissions play nice with minio.

**Comment by mimischi** [comment]
This has something to do with the UID that you specify. The UID of the user inside the Docker container and the UID of the storage folders owner have to be the same.

Doing some research on this, there are several solutions:

1. Mount `/etc/passwd` and `/etc/groups` as read-only, thus you can just use `USER dokku`, without adding that user explicitly. This _may_ have security implications, I don't know.
2. Specify some random UID for your `minio` user, `RUN adduser -D -u 12345 -g minio minio`. Then on the host one would need to `sudo chown -R 12345:12345 /var/lib/dokku/data/storage/minio`.
3. Use the same UID for the `dokku` user inside the `Dockerfile`, as on your host system. The problem here is, does every Dokku installation use the same UID for the `dokku` user? I think not, so that `Dockerfile` is not shareable.

I think solution number 2 is the best one. Currently waiting for an answer on the #dokku Gliderlabs Slack channel on any thoughts. **Update:** Choosing some random UID seems to be the go-to solution.
Number 1 exposes `/etc/passwd` and `/etc/groups` to the container, thus someone that managed to get access to the Docker container, but not host system (somehow), can know which users/groups exist on your host. Number 3 just does not work, when sharing the `Dockerfile`.
